disabled = false
locale = "en"
label = "English"
weight = 1
title = "Extrone"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/headericon.png"
  secondaryLogo = "img/Profile_400x400.png"
  description = "My awesome website"
  copyright = "2026 Arjun Subhash"

[params.author]
  name = "Extrone"
  email = "anjana4760@gmail.com"
  image = "img/Profile_400x400.jpg"
  imageQuality = 96
  headline = "Making Games and Plugins in Unreal Engine"
  bio = ""
  links = [
    { email = "mailto:anjana4760@gmail.com.com" },
    { discord = "https://discord.gg/w4xrhDSv8J" },
    { instagram = "https://instagram.com/arjun_subhash_" },
    { twitter = "https://twitter.com/extr0ne" },
    { youtube = "https://youtube.com/@Extrone" },
    { link = "https://extrone.bio.link"}
  ]
