baseURL = "https://extrone.github.io/"
languageCode = "en-us"
title = "Arjun Subhash"
theme = "PaperMod"

[params]
ShowBreadCrumbs = true
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowShareButtons = true
author = "Arjun Subhash"

  [params.profileMode]
  enabled = true
  title = "Arjun Subhash"
  subtitle = "UI Artist"
  imageUrl = "img/Profile_400x400.jpg"
  imageWidth = 256
  imageHeight = 256

    [[params.profileMode.buttons]]
    name = "Portfolio"
    url = "/portfolio/"

    [[params.profileMode.buttons]]
    name = "Games"
    url = "https://extrone.itch.io"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:anjana4760@gmail.com"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/extr0ne"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.gamedev.place/@extrone"

  [params.cover]
  LinkFullImages = true

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 4
